### PR TITLE
Automatically generate main file for unit tests

### PR DESCRIPTION
**Pull request by bartlomieju**
This commit implements automatic generation of the main file (inko-tests.inko) for running unit tests. This file is placed in the build/ directory and is regenerated on each run. The file is not removed after the tests are run to allow inspection.

Changelog: added

Closes https://github.com/inko-lang/inko/issues/575

### CODE REVIEW

**Comment by bartlomieju** [comment]
I believe with this change `std/test/main.inko` can (and should) be removed.

**Comment by yorickpeterse** [comment]
@bartlomieju Thanks for the changes! I made a couple of changed and amended those to your commit, then pushed it to your fork. I figured this was easier than writing a whole bunch of comments which you'd then have to piece together into actual code. I made the following changes:

- Some formatting changes here and there (e.g. an empty line after a `let` that spans multiple lines)
- I renamed a few of the new functions to be a bit shorter, and removed the comments as they weren't really needed
- Some of the code could be condensed a bit, so I did that
- The initial commit assumed the `build/` directory was already in place, and would error if this wasn't the case. I fixed this by ensuring the `build/` directory is created before the generated file is written
- The test file generator is changed a bit to not create a bunch of intermediate `String` values by using `push_str` instead. 
- A few other minor (read: pedantic) changes

You can see the exact list of changes [here](https://github.com/inko-lang/inko/compare/cd8c68427d7e78368bac038a917e6910bb2436b5..2ae707c200a600fc34b0f2a8120a0d8e856a923b).

**Comment by bartlomieju** [comment]
> [bartlomieju](https://github.com/bartlomieju) Thanks for the changes! I made a couple of changed and amended those to your commit, then pushed it to your fork. I figured this was easier than writing a whole bunch of comments which you'd then have to piece together into actual code. These changes are largely style related, and the general idea of your implementation was fine 😄

Totally and thanks! These changes make sense - since it's my first PR to the project I played it safe and erred on the verbose side :)

> The initial commit assumed the build/ directory was already in place, and would error if this wasn't the case. I fixed this by ensuring the build/ directory is created before the generated file is written

Nice catch, I completely missed that!

> I'll merge the PR some time tomorrow in case I think of anything else overnight.

SGTM; I assume you are going to delete `std/test/main.inko` in a follow up PR?

**Comment by yorickpeterse** [comment]
@bartlomieju 

> SGTM; I assume you are going to delete std/test/main.inko in a follow up PR?

And this is exactly why I wanted to wait with merging, I forgot about doing just that. Thanks for the reminder :smile:

**Comment by yorickpeterse** [comment]
@bartlomieju Thanks!

**Pull request merged**
